version: '3'
services:
  redis:
    image: redis:alpine
    container_name: sc-redis
    restart: always
    volumes:
      - ../data/redis:/data
    environment:
      - REDIS_PASSWORD=shudunR@6379edis
    networks:
      - sc-net
    ports:
      - 6379:6379
    env_file: .env

  mysql:
    image: mysql:8.0
    container_name: sc-mysql
    restart: always
    networks:
      - sc-net
    ports:
      - 3306:3306
    volumes:
      - ../data/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: shudun@123

networks:
  sc-net:
    external: false
